version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_issues = [
  "PY-D0001",
  "PY-D0002",
  "PY-D0003",
  "PY-D0004"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[code_formatters]]
name = "ruff"