version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  # Value should be in "x.y" format. DeepSource automatically uses the latest patch.
  runtime_version = "3.11"
  
  # Skipping the complete set of docstring issues (Module, Class, Function, Method)
  skip_issues = [
    "PY-D0001", # Missing docstring in public module
    "PY-D0002", # Missing docstring in public class
    "PY-D0003", # Missing docstring in public function
    "PY-D0004"  # Missing docstring in public method
  ]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true