services:
  price-spy:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: price_spy
    env_file:
      - ../.env
    volumes:
      - ../tests/screenshots:/app/tests/screenshots
      - ../data:/app/data
    stdin_open: true
    tty: true
