services:
  price-spy:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: price_spy
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../tests/screenshots:/app/tests/screenshots
      - ../data:/app/data
      - ../screenshots:/app/screenshots
    stdin_open: true
    tty: true
